Test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,57 +21,56 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Restore packages
-        run: npm install
-        working-directory: tasks/OrchestratorV2
-      - name: Run lint
-        run: npm run lint
-        working-directory: tasks/OrchestratorV2
-      - name: Run build
-        run: npm run build
-        working-directory: tasks/OrchestratorV2
-      - name: Run tests
-        run: npm run test
-        working-directory: tasks/OrchestratorV2
-      - name: Run clean
-        run: npm run clean
-        working-directory: tasks/OrchestratorV2
-      - name: Publish test results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        if: success() || failure()
-        with:
-          files: tasks/OrchestratorV2/tests/*.xml
-  build-v3:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Restore packages
-        run: npm install
-        working-directory: tasks/OrchestratorV3
-      - name: Run lint
-        run: npm run lint
-        working-directory: tasks/OrchestratorV3
-      - name: Run build
-        run: npm run build
-        working-directory: tasks/OrchestratorV3
-      - name: Run tests
-        run: npm run test
-        working-directory: tasks/OrchestratorV3
-      - name: Run clean
-        run: npm run clean
-        working-directory: tasks/OrchestratorV3
-      - name: Publish test results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        if: success() || failure()
-        with:
-          files: tasks/OrchestratorV3/tests/*.xml
-  package:
-    runs-on: ubuntu-latest
-    needs:
-      - build-v2
-      - build-v3
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install TFX CLI
-        run: npm install -g tfx-cli
+        run: ls -la
+      # - name: Run lint
+      #   run: npm run lint
+      #   working-directory: tasks/OrchestratorV2
+      # - name: Run build
+      #   run: npm run build
+      #   working-directory: tasks/OrchestratorV2
+      # - name: Run tests
+      #   run: npm run test
+      #   working-directory: tasks/OrchestratorV2
+      # - name: Run clean
+      #   run: npm run clean
+      #   working-directory: tasks/OrchestratorV2
+      # - name: Publish test results
+      #   uses: EnricoMi/publish-unit-test-result-action@v2
+      #   if: success() || failure()
+      #   with:
+      #     files: tasks/OrchestratorV2/tests/*.xml
+  # build-v3:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Restore packages
+  #       run: npm install
+  #       working-directory: tasks/OrchestratorV3
+  #     - name: Run lint
+  #       run: npm run lint
+  #       working-directory: tasks/OrchestratorV3
+  #     - name: Run build
+  #       run: npm run build
+  #       working-directory: tasks/OrchestratorV3
+  #     - name: Run tests
+  #       run: npm run test
+  #       working-directory: tasks/OrchestratorV3
+  #     - name: Run clean
+  #       run: npm run clean
+  #       working-directory: tasks/OrchestratorV3
+  #     - name: Publish test results
+  #       uses: EnricoMi/publish-unit-test-result-action@v2
+  #       if: success() || failure()
+  #       with:
+  #         files: tasks/OrchestratorV3/tests/*.xml
+  # package:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - build-v2
+  #     - build-v3
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Install TFX CLI
+  #       run: npm install -g tfx-cli
